Update Python_tests.yml: Remove deprecated 2.7 and 3.5
Those versions are removed anyway:

```
Error: Version 2.7 with arch x64 not found
Error: Version 3.6 with arch x64 not found
```